### ISSUE TITLE
Firefox error when using italic variable woff2 font file

### ISSUE THREAD

**Issue by nevadascout** [supernotes/sn-pro#12]
Firefox seems to not recognise the `SNPro-VariableItalic.woff2` file properly. It logs out these two console errors and it doesn't load the font properly.

This means that we use the italic variant of SN Pro in Firefox!

```
downloadable font: avar: A required mapping (for -1, 0 or 1) is missing (font-family: "SN Pro" style:italic weight:200..900 stretch:100 src index:0) source: /assets/SNPro/SNPro-VariableItalic.woff2

downloadable font: Table discarded (font-family: "SN Pro" style:italic weight:200..900 stretch:100 src index:0) source: /assets/SNPro/SNPro-VariableItalic.woff2
```

According to what I read online, this is an issue with the font file itself. For example: https://forum.glyphsapp.com/t/3241-stat-avar-issues-errors-in-firefox/28925

**Comment by tobeagram** [comment]
Hi @nevadascout, thanks for the report.

This should already be fixed on the [next](https://github.com/supernotes/sn-pro/tree/next) branch. I've also upped the priority to release SN Pro 1.3 soon as well that will fix this on main.
