### ISSUE TITLE
Do you have a preferred description for packages?

### ISSUE THREAD

**Issue by LorenDB** [supernotes/sn-pro#4]
Howdy! I've [packaged SN Pro for openSUSE](https://build.opensuse.org/package/show/M17N:fonts/supernotes-snpro-fonts), but the description in your README isn't very great for a distribution package:

> A friendly new typeface that's open source and free for both personal and commercial use. We've carefully re-designed each character, improving support for Markdown and ligatures. This font family is continually being updated and improved.

Do you have a better description that you would like packages to use or am I good to just come up with something myself?

**Comment by tobeagram** [comment]
Hi @LorenDB, makes sense thanks for asking. We will update / add a better description this week for you to use!

**Comment by LorenDB** [comment]
Thanks! If you remember, ping me once you've added it :)

**Comment by tobeagram** [comment]
Hi @LorenDB, we've come up with the following:

> SN Pro is a friendly sans serif typeface optimized for use with Markdown. It is based on Nunito by Vernon Adams, and each character has been re-worked to improve readability and usability within a Markdown context. Originally designed by and for Supernotes.

We aren't too familiar with the description etiquette or details required on openSUSE. If you have any edits or suggestions feel free to let us know :)

**Comment by LorenDB** [comment]
That looks good to me! Thank you so much!
