### ISSUE TITLE
Sorry, Kudos

### ISSUE THREAD

**Issue by fuzenco** [supernotes/sn-pro#6]
I know this isn’t an issue, but thanks for making this Open Source. It’s a beautiful refinement. I appreciate your adherence to excellence.

**Comment by tobeagram** [comment]
Thanks for the kind words @fuzenco! We'll continue to make SN Pro better with every update. Totally optional but if you're using SN Pro for a commercial project we encourage you to [sponsor the typeface](https://supernotes.app/open-source/sn-pro/#sponsor) ❤️
