### ISSUE TITLE
Homebrew Formula

### ISSUE THREAD

**Issue by gkaissis** [supernotes/sn-pro#7]
Could you please add a Homebrew Formula so Mac users can update via brew? Thanks for the great work!

**Comment by tobeagram** [comment]
Hi @gkaissis, thanks for your kind words, this was recently [brought up on HN](https://news.ycombinator.com/item?id=39478104) (posted my response below for future reference). 

> Seems like `homebrew/cask-fonts` is the best way to go for Homebrew, but even the repo maintainers [suggest that submission to Google Fonts is their desired method to be included](https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md). Once / if SN Pro garners more mainstream popularity we will start supporting more methods of distribution.

We'll start adding more methods of distribution once the font starts to get popular, as maintaining many different channels of distribution with each update will be a challenge.

**Comment by gkaissis** [comment]
Sounds great! Closing as this is already on your radar. Thanks!
