### ISSUE TITLE
Include SN Pro in the fontsource project

### ISSUE THREAD

**Issue by buhodev** [supernotes/sn-pro#8]
Hi, thanks for the great work with this font! I just saw that the variable version is on the works and I thought that it would be a nice idea to include SN Pro as a [fontsource](https://github.com/fontsource/fontsource) font once the variable version is ready: https://github.com/fontsource/font-files

I could [submit](https://github.com/fontsource/font-files/blob/main/CONTRIBUTING.md) SN Pro font if you agree.

**Comment by tobeagram** [comment]
Hi @buhodev,

Feel free to include SN Pro in the fontsource project! We've just pushed a WIP variable version on the new next branch, [read here for more details](https://github.com/supernotes/sn-pro/issues/1).

**Comment by connebs** [comment]
We've gone ahead and submitted a [PR to fontsource](https://github.com/fontsource/font-files/pull/69), hopefully it will be merged soon!

**Comment by connebs** [comment]
Our PR has been merged, you can check out [SN Pro on Fontsource here](https://fontsource.org/fonts/sn-pro/).
